### ISSUE TITLE
Add support for tokens BNTY and MKR

### ISSUE THREAD

**Issue by tipsysquid** [RequestNetwork/requestNetwork-v1-archive#5]
**Summary**
Seeking to add support for ERC20 tokens [BNTY](https://etherscan.io/token/0xd2d6158683aee4cc838067727209a0aaf4359de3) and [MRK](https://etherscan.io/token/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2) 

**Status** 
I followed the documentation and guides [Request Smart Contracts Documentation ](https://docs-smart-contracts.request.network/)and [Adding support for a new currency](https://docs.request.network/development/v1/guides/adding-support-for-a-new-currency#adding-a-new-erc20-token)

I have already deployed the contracts and verified their sources
[RequestERC20-BNTY](https://etherscan.io/address/0xfa7b14e5e5e0b59ef6fb86f56928349eb607cbb3)
[RequestERC20-MKR](https://etherscan.io/address/0x23d33c46f64ef9afec6a19e7ad758e99c87ae129)

**Follow up**
As per the [Contribution Guide](https://github.com/RequestNetwork/requestNetwork/blob/development/CONTRIBUTING.md), I am opening up this issue to begin discussions for these changes. Once satisfied, I will create a PR for this issue.

**Comment by vrolland** [comment]
HI Guys,

I have prepared the library to support the two tokens:  https://github.com/RequestNetwork/requestNetwork-v1-archive/pull/4

The next steps to close the issue are: 

1. **Change the burner address @tipsysquid**
2. **Transfer the ownership @tipsysquid**
3. Update the fees on the contracts @vrolland 
4. Autorized the contracts on the request core @vrolland 
5. Test creation and payments @vrolland 
6. Merge & Publish Library and Artifacts changes @vrolland 
7. Update the doc @vrolland 
8. Have a beer :beer: (all - optional)

Cheers,

**Comment by tipsysquid** [comment]
I have completed the following: 

- [x] Change the burner addresses 

- [x] Transfer ownership to Request Admin address `0x74ef019c1e9f11366c5c8dc4ab556c16fe13b51f`

You can follow the transactions from the previous owner address [here](https://etherscan.io/address/0xaFFF836C3c56fa413688b56A85499c109D8D26A5)

Thanks for providing the guidelines @vrolland! :rocket:

**Comment by vrolland** [comment]
@AngeloAdam Can you contact me in private on the slack "request hub" please?

**Comment by vrolland** [comment]
done #7  :beers:
